# Generated by Django 4.2.5 on 2023-11-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_info',
            fields=[
                ('channel_no', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='通道序号')),
                ('channel_status', models.CharField(default='未配置', max_length=30, verbose_name='通道状态')),
                ('address', models.CharField(default='rtsp://xxxxx', max_length=100, verbose_name='RTSP地址')),
                ('channel_name', models.CharField(default='ID_xx', max_length=30, verbose_name='通道名称')),
                ('person_status', models.CharField(default='开', max_length=30, verbose_name='算法-人数统计开关状态')),
                ('person_sensitive', models.IntegerField(verbose_name='算法-人数统计灵敏度')),
                ('person_frequency', models.IntegerField(verbose_name='算法-人数统计频率')),
                ('car_status', models.CharField(default='开', max_length=30, verbose_name='算法-车辆统计开关状态')),
                ('car_sensitive', models.IntegerField(verbose_name='算法-车辆统计灵敏度')),
                ('car_frequency', models.IntegerField(verbose_name='算法-车辆统计频率')),
                ('change_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'change_channel_no_profile',
            },
        ),
    ]
