# Generated by Django 4.2.5 on 2023-11-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel_info',
            table='channel_info',
        ),
    ]
