# Generated by Django 4.2.5 on 2023-11-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0002_alter_channel_info_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_info',
            name='change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
