# Generated by Django 4.2.5 on 2023-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0003_alter_channel_info_change_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_info',
            name='week',
            field=models.CharField(default='', max_length=30, verbose_name='周界'),
        ),
    ]
